import React, { useState, useRef, useEffect, useMemo } from 'react';
import { 
  Languages, 
  ChevronDown, 
  Download, 
  Bookmark, 
  Copy, 
  Share2, 
  Maximize2, 
  Minimize2, 
  Check, 
  Sparkles, 
  List, 
  FileCode, 
  Image as ImageIcon, 
  FileText
} from 'lucide-react';
import { StructuredSummary } from '../../types/summary';
import { InfographicData, InfographicLanguage } from '../../types/infographic';
import { buildInfographicFromSummary } from '../../services/infographicService';

interface InfographicViewProps {
  summary: StructuredSummary;
  initialLanguage?: InfographicLanguage;
}

export const InfographicView: React.FC<InfographicViewProps> = ({
  summary,
  initialLanguage = 'ar'
}) => {
  const [language, setLanguage] = useState<InfographicLanguage>(initialLanguage);
  const [isFullScreen, setIsFullScreen] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [copied, setCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const containerRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);

  const infographic: InfographicData = useMemo(() => {
    return buildInfographicFromSummary(summary, language);
  }, [summary, language]);

  const isRTL = language === 'ar';

  // Fullscreen sync
  useEffect(() => {
    const handleFullscreenChange = () => {
      setIsFullScreen(Boolean(document.fullscreenElement));
    };
    document.addEventListener('fullscreenchange', handleFullscreenChange);
    return () => document.removeEventListener('fullscreenchange', handleFullscreenChange);
  }, []);

  const toggleFullScreen = async () => {
    try {
      if (!isFullScreen) {
        if (containerRef.current?.requestFullscreen) {
          await containerRef.current.requestFullscreen();
        } else {
          setIsFullScreen(true);
        }
      } else {
        if (document.fullscreenElement) {
          await document.exitFullscreen();
        } else {
          setIsFullScreen(false);
        }
      }
    } catch {
      setIsFullScreen(!isFullScreen);
    }
  };

  const handleCopyText = () => {
    const lines: string[] = [
      `# ${infographic.title}`,
      infographic.subtitle,
      ''
    ];
    infographic.sections.forEach((s) => {
      lines.push(`## ${s.stepNumber} ${s.title}`);
      s.cards.forEach((c) => {
        lines.push(`### [${c.tag}] ${c.title}`);
        lines.push(c.description);
        lines.push('');
      });
    });

    navigator.clipboard.writeText(lines.join('\n'));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSaveMarkdown = () => {
    const lines: string[] = [
      `# ${infographic.title}`,
      `*Video: ${summary.video.title} (${summary.video.channel})*`,
      `*Language: ${language.toUpperCase()} | Generated by VidBrief.ai*`,
      '',
      infographic.subtitle,
      '',
      '---',
      ''
    ];

    infographic.sections.forEach((s) => {
      lines.push(`## ${s.stepNumber} ${s.title}`);
      s.cards.forEach((c) => {
        lines.push(`### [${c.tag}] ${c.title}`);
        lines.push(c.description);
        lines.push('');
      });
    });

    const blob = new Blob([lines.join('\n')], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${infographic.title.slice(0, 30).replace(/[\s/\\?%*:|"<>]+/g, '_')}_infographic.md`;
    link.click();
    URL.revokeObjectURL(url);
    setShowExportMenu(false);
  };

  // Export to PNG Image
  const exportToPNG = () => {
    setIsExporting(true);
    setShowExportMenu(false);

    try {
      const canvas = document.createElement('canvas');
      const width = 2000;
      const height = 2400;
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext('2d');

      if (!ctx) {
        setIsExporting(false);
        return;
      }

      // Background
      ctx.fillStyle = '#FFFFFF';
      ctx.fillRect(0, 0, width, height);

      // Top brand badge
      ctx.fillStyle = '#2563EB';
      ctx.font = 'bold 24px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
      ctx.textAlign = isRTL ? 'right' : 'left';
      ctx.fillText('VidBrief.ai — Visual Infographic', isRTL ? width - 80 : 80, 70);

      // Title
      ctx.fillStyle = '#0F172A';
      ctx.font = 'bold 36px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
      ctx.textAlign = isRTL ? 'right' : 'left';
      ctx.fillText(infographic.title.slice(0, 60), isRTL ? width - 80 : 80, 140);

      // Subtitle
      ctx.fillStyle = '#64748B';
      ctx.font = '20px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
      ctx.fillText(infographic.subtitle.slice(0, 100) + '...', isRTL ? width - 80 : 80, 190);

      // Separator Line
      ctx.strokeStyle = '#E2E8F0';
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(80, 225);
      ctx.lineTo(width - 80, 225);
      ctx.stroke();

      let currentY = 270;

      // Render sections
      infographic.sections.forEach((sec) => {
        // Section Header bar
        ctx.fillStyle = '#4D7C0F';
        ctx.fillRect(isRTL ? width - 150 : 80, currentY, 60, 36);

        ctx.fillStyle = '#FFFFFF';
        ctx.font = 'bold 20px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText(sec.stepNumber, isRTL ? width - 120 : 110, currentY + 26);

        ctx.fillStyle = '#0F172A';
        ctx.font = 'bold 24px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
        ctx.textAlign = isRTL ? 'right' : 'left';
        ctx.fillText(sec.title, isRTL ? width - 170 : 160, currentY + 27);

        // Green underline
        ctx.strokeStyle = '#4D7C0F';
        ctx.lineWidth = 3;
        ctx.beginPath();
        ctx.moveTo(80, currentY + 45);
        ctx.lineTo(width - 80, currentY + 45);
        ctx.stroke();

        currentY += 75;

        // Cards in row
        const cardWidth = (width - 200) / Math.max(sec.cards.length, 2);

        sec.cards.forEach((card, cIdx) => {
          const cardX = isRTL 
            ? width - 80 - (cIdx + 1) * cardWidth - cIdx * 20 
            : 80 + cIdx * (cardWidth + 20);

          // Card Box
          ctx.fillStyle = '#FFFFFF';
          ctx.strokeStyle = '#CBD5E1';
          ctx.lineWidth = 2;
          ctx.beginPath();
          ctx.roundRect(cardX, currentY, cardWidth, 230, 20);
          ctx.fill();
          ctx.stroke();

          // Tag Pill
          ctx.fillStyle = card.tagColor || '#10B981';
          ctx.beginPath();
          ctx.roundRect(isRTL ? cardX + cardWidth - 110 : cardX + 20, currentY + 15, 90, 30, 10);
          ctx.fill();

          ctx.fillStyle = '#FFFFFF';
          ctx.font = 'bold 15px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
          ctx.textAlign = 'center';
          ctx.fillText(card.tag, isRTL ? cardX + cardWidth - 65 : cardX + 65, currentY + 36);

          // Card Title
          ctx.fillStyle = '#0F172A';
          ctx.font = 'bold 20px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
          ctx.textAlign = isRTL ? 'right' : 'left';
          ctx.fillText(card.title.slice(0, 32), isRTL ? cardX + cardWidth - 25 : cardX + 25, currentY + 80);

          // Card Divider
          ctx.strokeStyle = '#F1F5F9';
          ctx.lineWidth = 1.5;
          ctx.beginPath();
          ctx.moveTo(cardX + 20, currentY + 95);
          ctx.lineTo(cardX + cardWidth - 20, currentY + 95);
          ctx.stroke();

          // Card Description
          ctx.fillStyle = '#475569';
          ctx.font = '16px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
          ctx.textAlign = isRTL ? 'right' : 'left';
          ctx.fillText(card.description.slice(0, 60), isRTL ? cardX + cardWidth - 25 : cardX + 25, currentY + 125);
          ctx.fillText(card.description.slice(60, 120), isRTL ? cardX + cardWidth - 25 : cardX + 25, currentY + 155);
          ctx.fillText(card.description.slice(120, 180), isRTL ? cardX + cardWidth - 25 : cardX + 25, currentY + 185);
        });

        currentY += 280;
      });

      canvas.toBlob((blob) => {
        if (!blob) return;
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${infographic.title.slice(0, 30).replace(/[\s/\\?%*:|"<>]+/g, '_')}_infographic.png`;
        link.click();
        URL.revokeObjectURL(url);
        setIsExporting(false);
      }, 'image/png');
    } catch (err) {
      console.error('PNG export failed:', err);
      setIsExporting(false);
    }
  };

  // Export to Standalone HTML
  const exportToHTML = () => {
    setShowExportMenu(false);
    const safeTitle = infographic.title.replace(/"/g, '&quot;');
    const html = `<!DOCTYPE html>
<html lang="${language}" dir="${isRTL ? 'rtl' : 'ltr'}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${safeTitle} — VidBrief Infographic</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&display=swap" rel="stylesheet">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #F8FAFC;
      color: #0F172A;
      padding: 40px 20px;
    }
    .container {
      max-width: 1040px;
      margin: 0 auto;
      background: #FFFFFF;
      border: 1px solid #E2E8F0;
      border-radius: 24px;
      padding: 40px;
      box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);
    }
    .hero-title {
      font-size: 28px;
      font-weight: 800;
      color: #0F172A;
      line-height: 1.35;
      margin-bottom: 12px;
    }
    .hero-subtitle {
      font-size: 14px;
      color: #64748B;
      line-height: 1.6;
      margin-bottom: 24px;
    }
    .separator {
      height: 1px;
      background: #E2E8F0;
      margin-bottom: 32px;
    }
    .section-wrap {
      margin-bottom: 36px;
    }
    .section-header {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 8px;
    }
    .step-badge {
      background: #D9F99D;
      color: #365314;
      font-weight: 800;
      font-size: 12px;
      padding: 4px 10px;
      border-radius: 6px;
    }
    .section-title {
      font-size: 18px;
      font-weight: 800;
      color: #0F172A;
    }
    .section-line {
      height: 3px;
      background: #4D7C0F;
      border-radius: 2px;
      margin-bottom: 20px;
    }
    .cards-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
      gap: 20px;
    }
    .card {
      background: #FFFFFF;
      border: 1px solid #CBD5E1;
      border-radius: 16px;
      padding: 20px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.02);
    }
    .card-tag {
      display: inline-block;
      background: #ECFDF5;
      color: #065F46;
      border: 1px solid #A7F3D0;
      font-weight: 700;
      font-size: 11px;
      padding: 3px 10px;
      border-radius: 8px;
      margin-bottom: 14px;
    }
    .card-title {
      font-size: 15px;
      font-weight: 800;
      color: #0F172A;
      margin-bottom: 10px;
    }
    .card-desc {
      font-size: 13px;
      color: #475569;
      line-height: 1.6;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1 class="hero-title">${safeTitle}</h1>
    <p class="hero-subtitle">${infographic.subtitle}</p>
    <div class="separator"></div>

    ${infographic.sections.map(sec => `
      <div class="section-wrap">
        <div class="section-header">
          <span class="step-badge">${sec.stepNumber}</span>
          <h2 class="section-title">${sec.title}</h2>
        </div>
        <div class="section-line"></div>
        <div class="cards-grid">
          ${sec.cards.map(card => `
            <div class="card">
              <span class="card-tag">${card.tag}</span>
              <h3 class="card-title">${card.title}</h3>
              <p class="card-desc">${card.description}</p>
            </div>
          `).join('')}
        </div>
      </div>
    `).join('')}
  </div>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${infographic.title.slice(0, 30).replace(/[\s/\\?%*:|"<>]+/g, '_')}_infographic.html`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div 
      ref={containerRef}
      className={`relative flex flex-col w-full bg-white dark:bg-[#0D1321] transition-all select-none ${
        isFullScreen 
          ? 'fixed inset-0 z-50 w-screen h-screen overflow-y-auto rounded-none p-6 bg-white dark:bg-[#0D1321]' 
          : 'rounded-3xl border border-neutral-200/90 dark:border-neutral-800 shadow-xs overflow-hidden'
      }`}
      dir={isRTL ? 'rtl' : 'ltr'}
    >
      {/* ------------------------------------------------------------- */}
      {/* 1. Sub-Toolbar Matching Image                                 */}
      {/* ------------------------------------------------------------- */}
      <div className="px-5 py-3 border-b border-neutral-200/80 dark:border-neutral-800 flex items-center justify-between gap-4 bg-white/95 dark:bg-[#0D1321]/95 backdrop-blur-md sticky top-0 z-30">
        {/* Left: View Style & Language Dropdowns */}
        <div className="flex items-center gap-3">
          {/* Default Style Selector */}
          <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-neutral-200 dark:border-neutral-700 bg-neutral-50 dark:bg-neutral-800/80 text-xs font-semibold text-neutral-800 dark:text-neutral-200">
            <List className="w-4 h-4 text-neutral-500" />
            <span>Default</span>
          </div>

          {/* Language Selector */}
          <div className="relative flex items-center">
            <Languages className="w-4 h-4 text-neutral-500 absolute left-3 pointer-events-none" />
            <select
              value={language}
              onChange={(e) => setLanguage(e.target.value as InfographicLanguage)}
              className="appearance-none pl-9 pr-8 py-1.5 rounded-xl border border-neutral-200 dark:border-neutral-700 bg-neutral-50 dark:bg-neutral-800/80 text-xs sm:text-sm font-semibold text-neutral-800 dark:text-neutral-200 focus:outline-none focus:ring-2 focus:ring-blue-500 cursor-pointer shadow-2xs"
            >
              <option value="ar">Arabic (العربية)</option>
              <option value="en">English (English)</option>
              <option value="fr">French (Français)</option>
            </select>
            <ChevronDown className="w-3.5 h-3.5 text-neutral-400 absolute right-2.5 pointer-events-none" />
          </div>
        </div>

        {/* Right: Fullscreen Button & Export / Action Controls */}
        <div className="flex items-center gap-1.5 sm:gap-2">
          {/* Full Screen Toggle */}
          <button
            type="button"
            onClick={toggleFullScreen}
            className={`p-2 rounded-xl transition-colors cursor-pointer flex items-center gap-1.5 text-xs font-semibold ${
              isFullScreen 
                ? 'bg-blue-600 text-white shadow-sm' 
                : 'text-neutral-600 dark:text-neutral-300 hover:text-blue-600 hover:bg-neutral-100 dark:hover:bg-neutral-800'
            }`}
            title={isFullScreen ? 'Exit Fullscreen' : 'Enter Fullscreen'}
          >
            {isFullScreen ? <Minimize2 className="w-4 h-4" /> : <Maximize2 className="w-4 h-4" />}
            <span className="hidden md:inline">{isFullScreen ? 'Exit Fullscreen' : 'Full Screen'}</span>
          </button>

          {/* Export Dropdown Menu (PNG, HTML, Markdown) */}
          <div className="relative">
            <button
              type="button"
              onClick={() => setShowExportMenu(!showExportMenu)}
              disabled={isExporting}
              className="p-2 rounded-xl text-neutral-600 dark:text-neutral-300 hover:text-blue-600 hover:bg-neutral-100 dark:hover:bg-neutral-800 transition-colors cursor-pointer flex items-center gap-1"
              title="Export Infographic"
            >
              <Download className="w-4 h-4" />
              <ChevronDown className="w-3 h-3 opacity-60" />
            </button>

            {showExportMenu && (
              <div className="absolute right-0 mt-2 w-56 rounded-2xl bg-white dark:bg-[#131B2E] border border-neutral-200 dark:border-neutral-800 shadow-xl py-2 z-40 animate-fadeIn">
                <div className="px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-neutral-400">
                  Export Infographic
                </div>

                <button
                  type="button"
                  onClick={exportToPNG}
                  className="w-full px-3.5 py-2 text-left text-xs font-semibold text-neutral-700 dark:text-neutral-200 hover:bg-blue-50 dark:hover:bg-neutral-800/80 hover:text-blue-600 flex items-center gap-2.5 transition-colors cursor-pointer"
                >
                  <ImageIcon className="w-4 h-4 text-blue-600" />
                  <span>Export as PNG Image (.png)</span>
                </button>

                <button
                  type="button"
                  onClick={exportToHTML}
                  className="w-full px-3.5 py-2 text-left text-xs font-semibold text-neutral-700 dark:text-neutral-200 hover:bg-blue-50 dark:hover:bg-neutral-800/80 hover:text-blue-600 flex items-center gap-2.5 transition-colors cursor-pointer"
                >
                  <FileCode className="w-4 h-4 text-indigo-600" />
                  <span>Export as Standalone HTML (.html)</span>
                </button>

                <button
                  type="button"
                  onClick={handleSaveMarkdown}
                  className="w-full px-3.5 py-2 text-left text-xs font-semibold text-neutral-700 dark:text-neutral-200 hover:bg-blue-50 dark:hover:bg-neutral-800/80 hover:text-blue-600 flex items-center gap-2.5 transition-colors cursor-pointer"
                >
                  <FileText className="w-4 h-4 text-amber-600" />
                  <span>Export as Markdown Outline (.md)</span>
                </button>
              </div>
            )}
          </div>

          {/* Copy Outline */}
          <button
            type="button"
            onClick={handleCopyText}
            className="p-2 rounded-xl text-neutral-600 dark:text-neutral-300 hover:text-blue-600 hover:bg-neutral-100 dark:hover:bg-neutral-800 transition-colors cursor-pointer relative"
            title="Copy outline"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
          </button>

          {/* Share */}
          <button
            type="button"
            onClick={handleCopyText}
            className="p-2 rounded-xl text-neutral-600 dark:text-neutral-300 hover:text-blue-600 hover:bg-neutral-100 dark:hover:bg-neutral-800 transition-colors cursor-pointer"
            title="Share"
          >
            <Share2 className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* ------------------------------------------------------------- */}
      {/* 2. Infographic Content Canvas                                 */}
      {/* ------------------------------------------------------------- */}
      <div 
        ref={contentRef}
        className="p-6 sm:p-10 space-y-8 bg-white dark:bg-[#0D1321] max-w-5xl mx-auto w-full"
      >
        {/* Floating Quick Fullscreen button on canvas matching screenshot */}
        <div className="flex justify-start">
          <button
            type="button"
            onClick={toggleFullScreen}
            className="p-2.5 rounded-xl border border-neutral-200/90 dark:border-neutral-700 bg-white dark:bg-[#131B2E] text-neutral-600 dark:text-neutral-300 hover:text-blue-600 hover:border-blue-500 shadow-xs transition-all cursor-pointer"
            title={isFullScreen ? 'Exit Fullscreen' : 'Enter Fullscreen'}
          >
            {isFullScreen ? <Minimize2 className="w-5 h-5" /> : <Maximize2 className="w-5 h-5" />}
          </button>
        </div>

        {/* Hero Title & Subtitle */}
        <div className="space-y-3">
          <h1 className="text-2xl sm:text-3xl lg:text-[32px] font-black text-neutral-900 dark:text-white tracking-tight leading-snug">
            {infographic.title}
          </h1>

          <p className="text-xs sm:text-sm text-neutral-500 dark:text-neutral-400 leading-relaxed max-w-4xl">
            {infographic.subtitle}
          </p>

          <div className="h-px bg-neutral-200/80 dark:border-neutral-800 pt-2" />
        </div>

        {/* Stats Pill Bar if available */}
        {infographic.statsBar && infographic.statsBar.length > 0 && (
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 p-4 rounded-2xl bg-neutral-50/80 dark:bg-neutral-900/60 border border-neutral-200/80 dark:border-neutral-800">
            {infographic.statsBar.map((stat, idx) => (
              <div key={idx} className="flex items-center gap-2.5">
                {stat.icon && <span className="text-xl shrink-0">{stat.icon}</span>}
                <div>
                  <p className="text-base font-black text-neutral-900 dark:text-white">{stat.value}</p>
                  <p className="text-[11px] text-neutral-500 font-medium">{stat.label}</p>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Structured Sections matching screenshot */}
        <div className="space-y-8 pt-2">
          {infographic.sections.map((sec) => (
            <div key={sec.id} className="space-y-4">
              {/* Section Header with Step Badge */}
              <div>
                <div className="flex items-center gap-2.5 mb-2">
                  <span className="px-2.5 py-0.5 rounded-lg bg-[#D9F99D] text-[#365314] text-xs font-black tracking-wide">
                    {sec.stepNumber}
                  </span>
                  <h2 className="text-base sm:text-lg font-black text-neutral-900 dark:text-white">
                    {sec.title}
                  </h2>
                </div>

                {/* Green Accent Line */}
                <div className="h-1 bg-[#4D7C0F] rounded-full w-full" />
              </div>

              {/* Cards Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {sec.cards.map((card) => (
                  <div
                    key={card.id}
                    className="p-5 rounded-2xl bg-white dark:bg-[#131B2E] border border-neutral-300 dark:border-neutral-700/80 shadow-xs hover:border-emerald-500/60 transition-all flex flex-col justify-between"
                  >
                    <div>
                      {/* Top Tag */}
                      <div className="flex items-center justify-start mb-3">
                        <span 
                          className="px-2.5 py-0.5 rounded-lg text-xs font-bold border"
                          style={{
                            backgroundColor: `${card.tagColor || '#10B981'}15`,
                            color: card.tagColor || '#10B981',
                            borderColor: `${card.tagColor || '#10B981'}40`
                          }}
                        >
                          {card.tag}
                        </span>
                      </div>

                      {/* Card Title */}
                      <h3 className="text-sm sm:text-base font-bold text-neutral-900 dark:text-white mb-2 leading-snug">
                        {card.title}
                      </h3>

                      <div className="h-px bg-neutral-100 dark:bg-neutral-800 my-2.5" />

                      {/* Card Description */}
                      <p className="text-xs sm:text-[13px] text-neutral-600 dark:text-neutral-300 leading-relaxed">
                        {card.description}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
